#!/bin/sh

# chkconfig: 345 99 01
# description: Elastic startup script

start() {
        echo "Starting ElasticSearch"
        /opt/elastic/start.sh
}

stop() {
        echo "Stopping ElasticSearch..."
        pkill -15 java
}

restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  *)
     echo "Usage: elastic {start|stop|restart}"
    exit 1
esac

exit 0
